In [1]:
from numpy import *

In [3]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [4]:
random.rand(4,4)

array([[ 0.93418522,  0.34364271,  0.86767324,  0.38795798],
       [ 0.57073884,  0.23127913,  0.65055582,  0.56244417],
       [ 0.77482643,  0.67737543,  0.39084759,  0.97630164],
       [ 0.00841093,  0.03362005,  0.68215172,  0.86963452]])

In [5]:
randMat = mat(random.rand(4,4))

In [6]:
randMat

matrix([[ 0.50976154,  0.33738195,  0.30436904,  0.65993965],
        [ 0.76034648,  0.67721113,  0.72650521,  0.07774253],
        [ 0.51038906,  0.61816499,  0.27038907,  0.05246675],
        [ 0.74959539,  0.98415879,  0.85278704,  0.28237036]])

In [7]:
randMat.I

matrix([[ 0.93812391,  2.86829968,  1.55304244, -3.27080043],
        [-0.6704461 , -2.7139002 ,  1.80706692,  1.97835385],
        [-0.50297445,  1.04447175, -3.2426468 ,  1.49046815],
        [ 1.36537753, -1.30986645, -0.62792376,  0.82767426]])

In [8]:
randMat.I * randMat

matrix([[  1.00000000e+00,   0.00000000e+00,   4.44089210e-16,
           0.00000000e+00],
        [  0.00000000e+00,   1.00000000e+00,   2.22044605e-16,
           0.00000000e+00],
        [ -4.44089210e-16,   0.00000000e+00,   1.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,   1.11022302e-16,   0.00000000e+00,
           1.00000000e+00]])

In [9]:
eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])